apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ms-one-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  defaultBackend: 
    service:
      name: pictochat
      port: 
        number: 30255
  rules:
  - http:
      paths:
        - path: /pictochat
          backend:
            name: pictochat
            port:
              number:  30255
        - path: /webapp
          backend:
            name: webapp
            port:
              number:  5678